### ISSUE TITLE
Organize transport of projects to/from design showcase

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#105]
We can rent a vehicle from fleet services if needed. The EFL trailer could be checked out but it requires the user to take some kind of course to get permission to use it which may be too much overhead.

**Comment by ixjlyons** [comment]
Not going to close this quite yet because I want to remember to add a few details about this to the instructor guide.

- reserved a flatbed truck from fleet services
- can drive on campus in a fleet services vehicle no problem, just go through the gate on Hutchison (near Silo)
- can get ratcheting tie-down straps from the EFL
