### ISSUE TITLE
Review microcontroller lesson and make improvements

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#53]
We should make some updates to this before moving forward this year. Some ideas (be sure to sure the list for more):

- We have increased the time from 1 hr to up to 3hrs in the lab portion so we can expand a bit or just give students more time to complete their microcontroller.
- Can we improve how the setup works interm of how to heat the sensor? Something more realistic?
- The lecture portion that went over coding was too little time to cover the material.
- We should get them to actually turn in the homework assignment for a grade this time.

**Comment by moorepants** [comment]
See this issue: https://github.com/moorepants/eme185/issues/14

**Comment by ixjlyons** [comment]
I came up with a pretty neat idea, though it involves a pretty serious overhaul of the lesson.

Wire up a [photocell](https://www.sparkfun.com/products/9088) in a voltage divider to an analog input pin, then put an LED on a PWM output. They can be set up on a breadboard so the LED can meaningfully influence the photocell's reading. You can take an ambient lighting measurement, then choose a setpoint a bit brigher than that. Then you write a controller to turn the LED brightness up or down to reach the set brightness level. Once it's running, you can move your hands around to create shadows to perturb the input and watch the LED get brighter to compensate. I tested it out and it works surprisingly well.

However, I just found that last year's BOM for getting the lesson materials includes components to implement this idea. Was there a big reason not to? It has quite a few advantages over the temperature controller: it's much more responsive to perturbations, it's visually appealing (can see the LED dim and brighten), and it's a simpler physical setup.

**Comment by moorepants** [comment]
This sounds quite nice. I don't recall what we discussed last year and why we choose what we did. Is the controller just a proportional controller? Something the can easily implement in a few lines of code?

What BOM are you talking about?

I'm willing to go with this. Can you give me an idea of how much it would cost for new hardware?

Also, are you (and other TAs) willing to redo the lab portion (mainly the slides)?

**Comment by ixjlyons** [comment]
- I spent very little time playing with controller gains, but a proportional controller can work but gives steady state error (kind of cool to demo that I think), and an integral term can get rid of it.
- The folder from last year with the Arduino lessons has a pricing spreadsheet with costs of components.
- ~$70 for 50 of everything required (aside from what we already have).
- I'm willing to do it because I can't really get the temperature controller to work well at all.

Here's a screenshot to show it in action. It's just the 10-bit reading from the sensor subtracted from 1023 to turn it into a "brightness" value. I'll mess around with it a little more to see if it can be a little cleaner (I think Kp is a bit high maybe):

![light-controller](https://cloud.githubusercontent.com/assets/943602/22847813/8490adac-efa4-11e6-9c67-02971a04603a.png)

**Comment by Gangchen01** [comment]
It is better to give a detail example, i.e. LED brightness control during the lecture, include the controller design, program design. After the lecture, students can know how to writer code to read the signal and set the pins of the micro controller. 

The example will act as a template for the student, thus they just need to add function to the example code for their own project. In that case, DAC, ADC, PWM, IO read/write, while/if else  program should be included.

**Comment by ixjlyons** [comment]
This has been settled on. Tutorial can be found [here](https://moorepants.github.io/eme185/pages/part-2-implementing-a-pi-controller-with-an-arduino.html)
