### ISSUE TITLE
Upload the presentation 2 grades

### ISSUE THREAD

**Issue by moorepants** [moorepants/eme185#87]
@ixjlyons Can you convert the google sheets to pdfs with the individual scorer's scores hidden and post these grades to the canvas assignment?

This script used to work: https://github.com/moorepants/eme185/blob/master/bin/convertToPDF.gs but it's probably just faster to do it manually.

**Comment by ixjlyons** [comment]
So, for the record, running the script and adding the [`muteHttpExceptions`](https://developers.google.com/apps-script/reference/url-fetch/url-fetch-app#fetch(String,Object)) option allowed me to see the response when the script fails after processing a handful of the sheets:

> Wow, this file is really popular! It might be unavailable until the crowd clears.

I added a `Utilities.sleep(500)` at the end of the big loop over all of the sheets, but that didn't quite do it. Anyway, all the PDFs are generated now since I just did them in several passes.

**Comment by ixjlyons** [comment]
Uploaded to Canvas and grades entered.
